# -*- coding: utf-8 -*-
"""生成港股（hk）选股默认股票池 ``src/data/hk_universe.txt``。

从前端自动补全索引 ``apps/dsa-web/public/stocks.index.json`` 提取港股代码，转成
yfinance 习惯的 ``<4位>.HK``（如 ``0700.HK``、``9988.HK``）。港股选股走 yfinance
（与美股/新加坡同路径，快且稳），无需在线代码表。

用法：

    python scripts/fetch_hk_universe.py            # 重建 src/data/hk_universe.txt
    python scripts/fetch_hk_universe.py --dry-run  # 只打印统计

说明：默认股票池为静态可提交文件（与 us/sg/cn 一致）。运行时可用
``HK_SCREEN_UNIVERSE`` / ``HK_SCREEN_UNIVERSE_FILE`` 覆盖。
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
_INDEX_FILE = _ROOT / "apps" / "dsa-web" / "public" / "stocks.index.json"
_OUT_FILE = _ROOT / "src" / "data" / "hk_universe.txt"


def build_universe() -> list[str]:
    data = json.loads(_INDEX_FILE.read_text(encoding="utf-8"))
    codes: set[str] = set()
    for row in data:
        if not isinstance(row, list) or len(row) < 7:
            continue
        display, market = row[1], row[6]
        if market != "HK":
            continue
        digits = "".join(ch for ch in str(display) if ch.isdigit())
        if not digits:
            continue
        # yfinance 港股格式：4 位补零（<10000），更大保持原样
        num = int(digits)
        if num <= 0:
            continue
        codes.add(f"{num:04d}.HK")
    return sorted(codes)


def main() -> int:
    parser = argparse.ArgumentParser(description="重建港股选股默认股票池")
    parser.add_argument("--dry-run", action="store_true", help="只打印统计，不写文件")
    args = parser.parse_args()

    try:
        codes = build_universe()
    except Exception as exc:  # noqa: BLE001
        print(f"[ERROR] 读取索引失败 {_INDEX_FILE}: {exc}", file=sys.stderr)
        return 1

    print(f"从索引提取港股：{len(codes)} 只")
    if args.dry_run:
        return 0

    header = (
        "# HK screening default universe: Hong Kong equities (yfinance <4d>.HK)\n"
        "# Generated by scripts/fetch_hk_universe.py from apps/dsa-web/public/stocks.index.json.\n"
        "# Override via HK_SCREEN_UNIVERSE(_FILE).\n"
    )
    _OUT_FILE.write_text(header + "\n".join(codes) + "\n", encoding="utf-8")
    print(f"已写入 {_OUT_FILE}（{len(codes)} 只）")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
