# -*- coding: utf-8 -*-
"""生成 A 股（cn）选股默认股票池 ``src/data/cn_universe.txt``。

从前端自动补全索引 ``apps/dsa-web/public/stocks.index.json``（已含约 5200 只 A 股 +
北交所）提取 6 位代码，避免再依赖 akshare 在线代码表（东方财富接口间歇性断连）。

用法：

    python scripts/fetch_cn_universe.py            # 重建 src/data/cn_universe.txt
    python scripts/fetch_cn_universe.py --dry-run  # 只打印统计

说明：默认股票池为静态可提交文件（与 us/sg 一致），确定性、运行时不依赖网络。
选股运行时仍可用 ``CN_SCREEN_UNIVERSE`` / ``CN_SCREEN_UNIVERSE_FILE`` 覆盖。
A 股全市场首次回填较慢（akshare 逐只，约 8s/只），建议用 ``scripts/sync_prices.py
--markets cn`` 后台增量灌缓存。
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
_INDEX_FILE = _ROOT / "apps" / "dsa-web" / "public" / "stocks.index.json"
_OUT_FILE = _ROOT / "src" / "data" / "cn_universe.txt"

# 纳入的市场标记（A 股主板/创业板/科创板=CN，北交所=BSE）
_KEEP_MARKETS = {"CN", "BSE"}


def build_universe() -> list[str]:
    data = json.loads(_INDEX_FILE.read_text(encoding="utf-8"))
    codes: set[str] = set()
    for row in data:
        if not isinstance(row, list) or len(row) < 7:
            continue
        display, market = row[1], row[6]
        if market not in _KEEP_MARKETS:
            continue
        bare = "".join(ch for ch in str(display) if ch.isdigit())[:6]
        if len(bare) == 6:
            codes.add(bare)
    return sorted(codes)


def main() -> int:
    parser = argparse.ArgumentParser(description="重建 A 股选股默认股票池")
    parser.add_argument("--dry-run", action="store_true", help="只打印统计，不写文件")
    args = parser.parse_args()

    try:
        codes = build_universe()
    except Exception as exc:  # noqa: BLE001
        print(f"[ERROR] 读取索引失败 {_INDEX_FILE}: {exc}", file=sys.stderr)
        return 1

    print(f"从索引提取 A 股（{sorted(_KEEP_MARKETS)}）：{len(codes)} 只")
    if args.dry_run:
        return 0

    header = (
        "# CN screening default universe: A-share (main/ChiNext/STAR) + Beijing exchange\n"
        "# Generated by scripts/fetch_cn_universe.py from apps/dsa-web/public/stocks.index.json.\n"
        "# 6-digit codes. Override via CN_SCREEN_UNIVERSE(_FILE).\n"
    )
    _OUT_FILE.write_text(header + "\n".join(codes) + "\n", encoding="utf-8")
    print(f"已写入 {_OUT_FILE}（{len(codes)} 只）")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
