# -*- coding: utf-8 -*-
"""生成新加坡（SGX）选股默认股票池 ``src/data/sg_universe.txt``。

从 SGX 官方证券列表接口拉取全表，过滤出主板**股票类**标的（普通股 / REITs /
商业信托），按 yfinance 习惯写成 ``<代码>.SI`` 形式（如 ``D05.SI``）。

排除：窝轮 / 结构性权证（companywarrants / structuredwarrants）、DLC
（dlcertificates）、ETF（etfs）、债券（bonds，接口已默认排除）、ADR、
挂牌凭证（listedcertificates）等非主板个股标的。

用法：

    python scripts/fetch_sg_universe.py            # 重建 src/data/sg_universe.txt
    python scripts/fetch_sg_universe.py --dry-run  # 只打印统计，不写文件

说明：默认股票池为静态可提交文件（与 ``us_universe.txt`` 一致），保证确定性、
不在运行时依赖网络。需要更新时手动重跑本脚本。选股运行时仍可用
``SG_SCREEN_UNIVERSE`` / ``SG_SCREEN_UNIVERSE_FILE`` 覆盖。
"""
from __future__ import annotations

import argparse
import json
import ssl
import sys
import urllib.request
from pathlib import Path

# SGX 官方证券列表接口（公开）。params 仅取代码/名称/类型，避免拉取无用行情字段。
SGX_API = (
    "https://api.sgx.com/securities/v1.1"
    "?excludetypes=bonds&params=nc,n,type"
)

# 视为「主板股票」纳入选股池的证券类型。
KEEP_TYPES = {"stocks", "reits", "businesstrusts"}

_OUT_FILE = Path(__file__).resolve().parent.parent / "src" / "data" / "sg_universe.txt"


def fetch_sgx_securities(timeout: int = 30) -> list[dict]:
    ctx = ssl.create_default_context()
    # SGX 接口证书链在部分环境校验失败，且数据为公开列表，放宽校验仅用于本地生成。
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE
    req = urllib.request.Request(
        SGX_API,
        headers={"User-Agent": "Mozilla/5.0", "Accept": "application/json"},
    )
    with urllib.request.urlopen(req, context=ctx, timeout=timeout) as resp:
        data = json.loads(resp.read())
    return data.get("data", {}).get("prices", []) or []


def build_universe(records: list[dict]) -> list[str]:
    codes: set[str] = set()
    for r in records:
        if r.get("type") in KEEP_TYPES:
            code = (r.get("nc") or "").strip().upper()
            if code:
                codes.add(code)
    return sorted(codes)


def main() -> int:
    parser = argparse.ArgumentParser(description="重建 SGX 选股默认股票池")
    parser.add_argument("--dry-run", action="store_true", help="只打印统计，不写文件")
    args = parser.parse_args()

    try:
        records = fetch_sgx_securities()
    except Exception as exc:  # noqa: BLE001 - 命令行脚本，直接报错退出
        print(f"[ERROR] 拉取 SGX 列表失败：{exc}", file=sys.stderr)
        return 1

    by_type: dict[str, int] = {}
    for r in records:
        t = r.get("type") or "unknown"
        by_type[t] = by_type.get(t, 0) + 1
    print(f"SGX 返回 {len(records)} 条；类型分布：{by_type}")

    codes = build_universe(records)
    print(f"纳入主板股票池（{sorted(KEEP_TYPES)}）：{len(codes)} 只")

    if args.dry_run:
        return 0

    header = (
        "# SG screening default universe: SGX mainboard equities + REITs + business trusts\n"
        "# Generated by scripts/fetch_sg_universe.py from the SGX official securities list.\n"
        "# yfinance-style symbols (<code>.SI). Override via SG_SCREEN_UNIVERSE(_FILE).\n"
    )
    body = "\n".join(f"{c}.SI" for c in codes) + "\n"
    _OUT_FILE.write_text(header + body, encoding="utf-8")
    print(f"已写入 {_OUT_FILE}（{len(codes)} 只）")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
